# -*- coding: utf-8 -*-
"""LOOPS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1405Nf34WqrhN8MAHUkH58HC9BU1LkYF4

# LOOPS IN PYTHON
"""

# Armstrong numbers in a range
# Print all armstrong numbers between 1 and N.
n = int(input("enter the value of N:"))
print("armstrong numbers between 1 and", n, "are:")
for i in range(1 , n + 1):
  num = i
  total = 0
  digits = len(str(i))
  while num > 0:
    rem = num % 10
    total = total + rem ** digits
    num = num // 10
  if total == i:
    print(i)

# Find the largest digit in a number.
num = int(input("enter a number:"))
largest = 0
while num > 0:
  digit = num % 10
  if digit > largest:
    largest = digit
  num = num // 10
print("largest digit =", largest)

# Password strength checker (using loops)
# Check whether a password contains: Uppercase, Lowercase , digit, special character, minnimum 8 characters.
password = input("enter a password")
upper = 0
lower = 0
digit = 0
special = 0
for ch in password:
  if 'A' <= ch <= 'Z':
    upper = 1
  elif 'a' <= ch <= 'z':
    lower = 1
  elif '0' <= ch <= '9':
    digit = 1
  else:
    special = 1
    if len(password) >= 8 and upper and lower and digit and special:
      print("valid password")
    else:
      print("invalid password")

# Print Pascal's triangle
# Print the first N rows of pascal's triangle example (N=5)
n = int(input("enter the number of rows:"))
for i in range(n):
  num = 1
  for j in range(i + 1):
    print(num, end=" ")
    num = num * (i - j) // (j + 1)
  print()