# -*- coding: utf-8 -*-
"""MODULE1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kvWf1FBbw0kCTECHn2RzE2h0crAxwENC

## CONDITIONAL **STATEMENTS**
"""

# Write a program to check whether a year is a leap year or not.
year = int(input("enter a year"))
if year % 400 == 0:
  print("leap year")
elif year % 4 == 0:
  print(" not a leap year")
elif year % 100 == 0:
  print("leap year")

# Write a program to find the largest among three numbers using nested conditiopnal statements.
number = int(input("enter a number"))
n1 = int(input("enter first number:"))
n2 = int(input("enter second number"))
n3 = int(input("enter third number"))
if n1 > n2 and n1 > n3:
  print("n1 is the largest number")
if n2 > n1 and n2 > n3:
  print("n2 is the largest number")
else:
  print("n3 is the largest number")

# Write a program to calculate electricity bill using different unit slabs.
unit = int(input("enter number of units used"))
if unit > 0 and unit <= 100:
  print("unit*5")
if unit > 100 and unit <= 200:
  print("unit*10")
if unit > 201:
  print("unit*15")

# Write a program to check whether a character is an uppercase letter , lowercase letter , letter , digit or special character
char = input("enter a character:")
if char >= 'A' and char <= 'Z':
  print("Uppercase letter")
elif char >= 'a' and char <= 'z':
  print("Lowercase letter")
elif char >= '0' and char <= '9':
  print("Digit")
else:
  print("Special character")

# Write a program to determine whether a triangle is equilateral , isosceles , or scalene.
A = int(input("enter first side:"))
B = int(input("enter second side:"))
C = int(input("enter third side:"))
if A == B and B == C:
  print("equilateral triangle")
elif A == B and B == C and A == C:
  print("isosceles triangle")
else:
  print("scalene triangle")

# Write a program to create a simple calculator using if-elif-else.
num1 = float(input("enter first number:"))
num2 = float(input("enter second number:"))
op = input("enter operator (+, -, *, /):")
if op == '+':
  print("result =", num1 + num2)
elif op == '-':
  print("result =", num1 - num2)
elif op == '*':
  print("result =", num1 * num2)
elif op == '/':
  print("result =", num1 / num2)
else:
  print("division by zero is not possible")
  print("invalid operator")

# Write a program to assign grades based on marks and display distinction for high scores
marks = int(input("enter the marks:"))
if marks >= 90 and marks <=100:
  print("gradeA")
elif marks >= 80 and marks < 90:
  print("gradeB")
elif marks >= 70 and marks < 80:
  print("gradeC")
else:
  print("fail")

# Write a program to calculate income tax according to salary ranges.
salary = int(input("enter the annual salary:"))
if salary <= 250000:
  print("tax = 0")
elif salary <= 500000:
  print("tax = salary * 0.05")
elif salary <= 1000000:
  print("tax = salary * 0.20")
else:
  print("tax = salary * 0.30")
  print("income tax =", tax)

# Write a program to check login authentication using username and password conditions.
username = input("enter username:")
password = input("enter password:")
if username == "admin" and password == "1234":
  print("login successful")
else:
  print("invalid username or password")

from os import XATTR_REPLACE
# Write a program to determine whether a point lies in first quadrant, second quadrant, third quadrant, fourth quadrant, on axis or at origin
x = int(input("enter x-coordinate:"))
y = int(input("enter y-coordinate:"))
if x > 0 and y > 0:
  print("point lies in first quadrant")
elif x < 0 and y > 0:
  print("point lies in second quadrant")
elif x < 0 and y < 0:
  print("point lies in third quadrant")
elif x > 0 and y < 0:
  print("point lies in fourth quadrant")
elif x == 0 and y == 0:
  print("point lies at origin")
elif x == 0:
  print("point lies on y-axis")
else:
  print("point lies on x-axis")

"""# DICTIONARY AND SET"""

# Write a program to create a dictionary from two lists: one of keys and one of values.
keys = ["name" , "age" , "city"]
values = ["sonali" , 23 , "delhi"]
dictionary = dict(zip(keys, values))
print("Dictionary =", dictionary)

# Merge two dictionaries into one.
dictionary1 = {'name': 'sonali', 'age': 23, 'city': 'delhi'}
dictionary2 = {'course': 'B.tech'}
merge = dictionary1 | dictionary2
print("merged dictionary =", merge)

# Write a program to sort a dictionary by its values.
dictionary = {'A': 15, 'B': 25, 'C': 40, 'D': 50, 'E': 60}
sorted_values = sorted(dictionary.values())
print("sorted values:", sorted_values)

# Given two sets check if one set is subset of another.
set1 = {1,2,3}
set2 = {1,2,3,4,5}
if set1.issubset(set2):
  print("set1 is subset of set2")
else:
  print("set1 is not a subset of set2")

#  Write a program to check whether two lists have atleast one common element using sets.
list1 = [1,2,4,5,6]
list2 = [6,7,8,9,10]
A = set(list1)
B = set(list2)
if A.intersection(B):
  print("the lists have atleast one common element")
else:
  print("the lists have no common element")

"""# LISTS AND TUPLES"""

# Write a program to find the largest and smallest elements in a list.
List = [10,40,50,35,20,15]
largest = max(List)
smallest = min(List)
print("largest element:", largest)
print("smallest element:", smallest)

del list

# Write a program to remove duplicate elements from list.
numbers = [1,2,3,4,2,1,5]
unique = list(set(numbers))
print("list after removing duplicates:",unique)

# Write a program to reverse a list without using built in reverse functions.
L1 = [5,6,7,8,9,10]
L1.reverse()
print("reversed list:", L1)

# Write a program to count even and odd numbers in a list.
numbers = [2,3,7,8,5,1]
even = 0
odd = 0
for i in numbers:
  if i % 2 == 0:
    even += 1
  else:
    odd += 1
    print("number of even elements:", even)
    print("number of odd elements:", odd)

# Write a program to merge two lists and sort final list.
L1 = [1,2,3,4,5]
L2 = [6,7,8,9]
final_list = L1 + L2
final_list.sort()
print("merged and sorted list:", final_list)

# Write a program to find the second largest element in a list.
numbers = [3,4,5,7,8,9,2]
numbers.sort()
print("second largest element:", numbers[-2])

# Write a program to check whether an element exists in a tuple.
T1 = (10,20,45,60,35,50)
element = 20
if element in T1:
  print("element exists in the tuple")
else:
  print("element does not exist in the tuple")

# Write a program to count the occurence of an element in a tuple.
T1 = (1,2,2,3,4,5,6)
element = 2
count = T1.count(element)
print("occurence of", element, "is", count)

# Write a program to sort a list of tuples based on tuple values.
data = [(1,2), (4,6), (3,5), (7,2),(8,3)]
data.sort()
print("sorted list:", data)

# Write a program to convert a list into a tuple and a tuple into a list.
my_list = [50,60,70,80,90]
my_tuple = tuple(my_list)
print("tuple:", my_tuple)
my_tuple = (10,20,30,40,)
my_list = list(my_tuple)
print("list:", my_list)